/// Cross-platform virtual key codes
#[derive(Debug, Clone, Copy)]
pub enum VirtualKey {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Space,
    Enter,
    Tab,
    Escape,
    Backspace,
    Up,
    Down,
    Left,
    Right,
    Shift,
    Control,
    Alt,
}

impl VirtualKey {
    #[cfg(target_os = "windows")]
    pub fn to_windows_vk(&self) -> u16 {
        match self {
            VirtualKey::A => 0x41,
            VirtualKey::B => 0x42,
            VirtualKey::C => 0x43,
            VirtualKey::D => 0x44,
            VirtualKey::E => 0x45,
            VirtualKey::F => 0x46,
            VirtualKey::G => 0x47,
            VirtualKey::H => 0x48,
            VirtualKey::I => 0x49,
            VirtualKey::J => 0x4A,
            VirtualKey::K => 0x4B,
            VirtualKey::L => 0x4C,
            VirtualKey::M => 0x4D,
            VirtualKey::N => 0x4E,
            VirtualKey::O => 0x4F,
            VirtualKey::P => 0x50,
            VirtualKey::Q => 0x51,
            VirtualKey::R => 0x52,
            VirtualKey::S => 0x53,
            VirtualKey::T => 0x54,
            VirtualKey::U => 0x55,
            VirtualKey::V => 0x56,
            VirtualKey::W => 0x57,
            VirtualKey::X => 0x58,
            VirtualKey::Y => 0x59,
            VirtualKey::Z => 0x5A,
            VirtualKey::Num0 => 0x30,
            VirtualKey::Num1 => 0x31,
            VirtualKey::Num2 => 0x32,
            VirtualKey::Num3 => 0x33,
            VirtualKey::Num4 => 0x34,
            VirtualKey::Num5 => 0x35,
            VirtualKey::Num6 => 0x36,
            VirtualKey::Num7 => 0x37,
            VirtualKey::Num8 => 0x38,
            VirtualKey::Num9 => 0x39,
            VirtualKey::Space => 0x20,
            VirtualKey::Enter => 0x0D,
            VirtualKey::Tab => 0x09,
            VirtualKey::Escape => 0x1B,
            VirtualKey::Backspace => 0x08,
            VirtualKey::Up => 0x26,
            VirtualKey::Down => 0x28,
            VirtualKey::Left => 0x25,
            VirtualKey::Right => 0x27,
            VirtualKey::Shift => 0x10,
            VirtualKey::Control => 0x11,
            VirtualKey::Alt => 0x12,
        }
    }

    #[cfg(target_os = "linux")]
    pub fn to_linux_keycode(&self) -> u16 {
        // Linux keycodes from linux/input-event-codes.h
        match self {
            VirtualKey::A => 30,
            VirtualKey::B => 48,
            VirtualKey::C => 46,
            VirtualKey::D => 32,
            VirtualKey::E => 18,
            VirtualKey::F => 33,
            VirtualKey::G => 34,
            VirtualKey::H => 35,
            VirtualKey::I => 23,
            VirtualKey::J => 36,
            VirtualKey::K => 37,
            VirtualKey::L => 38,
            VirtualKey::M => 50,
            VirtualKey::N => 49,
            VirtualKey::O => 24,
            VirtualKey::P => 25,
            VirtualKey::Q => 16,
            VirtualKey::R => 19,
            VirtualKey::S => 31,
            VirtualKey::T => 20,
            VirtualKey::U => 22,
            VirtualKey::V => 47,
            VirtualKey::W => 17,
            VirtualKey::X => 45,
            VirtualKey::Y => 21,
            VirtualKey::Z => 44,
            VirtualKey::Num0 => 11,
            VirtualKey::Num1 => 2,
            VirtualKey::Num2 => 3,
            VirtualKey::Num3 => 4,
            VirtualKey::Num4 => 5,
            VirtualKey::Num5 => 6,
            VirtualKey::Num6 => 7,
            VirtualKey::Num7 => 8,
            VirtualKey::Num8 => 9,
            VirtualKey::Num9 => 10,
            VirtualKey::Space => 57,
            VirtualKey::Enter => 28,
            VirtualKey::Tab => 15,
            VirtualKey::Escape => 1,
            VirtualKey::Backspace => 14,
            VirtualKey::Up => 103,
            VirtualKey::Down => 108,
            VirtualKey::Left => 105,
            VirtualKey::Right => 106,
            VirtualKey::Shift => 42,
            VirtualKey::Control => 29,
            VirtualKey::Alt => 56,
        }
    }
}

/// Parse string key name to VirtualKey
pub fn parse_key(k: &str) -> Option<VirtualKey> {
    let upper = k.to_uppercase();
    match upper.as_str() {
        "SPACE" => Some(VirtualKey::Space),
        "ENTER" | "RETURN" => Some(VirtualKey::Enter),
        "TAB" => Some(VirtualKey::Tab),
        "ESC" | "ESCAPE" => Some(VirtualKey::Escape),
        "BACKSPACE" => Some(VirtualKey::Backspace),
        "UP" => Some(VirtualKey::Up),
        "DOWN" => Some(VirtualKey::Down),
        "LEFT" => Some(VirtualKey::Left),
        "RIGHT" => Some(VirtualKey::Right),
        "SHIFT" => Some(VirtualKey::Shift),
        "CTRL" | "CONTROL" => Some(VirtualKey::Control),
        "ALT" => Some(VirtualKey::Alt),
        "A" => Some(VirtualKey::A),
        "B" => Some(VirtualKey::B),
        "C" => Some(VirtualKey::C),
        "D" => Some(VirtualKey::D),
        "E" => Some(VirtualKey::E),
        "F" => Some(VirtualKey::F),
        "G" => Some(VirtualKey::G),
        "H" => Some(VirtualKey::H),
        "I" => Some(VirtualKey::I),
        "J" => Some(VirtualKey::J),
        "K" => Some(VirtualKey::K),
        "L" => Some(VirtualKey::L),
        "M" => Some(VirtualKey::M),
        "N" => Some(VirtualKey::N),
        "O" => Some(VirtualKey::O),
        "P" => Some(VirtualKey::P),
        "Q" => Some(VirtualKey::Q),
        "R" => Some(VirtualKey::R),
        "S" => Some(VirtualKey::S),
        "T" => Some(VirtualKey::T),
        "U" => Some(VirtualKey::U),
        "V" => Some(VirtualKey::V),
        "W" => Some(VirtualKey::W),
        "X" => Some(VirtualKey::X),
        "Y" => Some(VirtualKey::Y),
        "Z" => Some(VirtualKey::Z),
        "0" => Some(VirtualKey::Num0),
        "1" => Some(VirtualKey::Num1),
        "2" => Some(VirtualKey::Num2),
        "3" => Some(VirtualKey::Num3),
        "4" => Some(VirtualKey::Num4),
        "5" => Some(VirtualKey::Num5),
        "6" => Some(VirtualKey::Num6),
        "7" => Some(VirtualKey::Num7),
        "8" => Some(VirtualKey::Num8),
        "9" => Some(VirtualKey::Num9),
        _ => {
            tracing::warn!("Unknown key: {}", k);
            None
        }
    }
}
